# Generated by Django 4.2.5 on 2023-09-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField()),
                ('cupo_minimo', models.IntegerField()),
                ('cupo_maximo', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('fecha_creacion_proyecto', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualización_proyecto', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
            },
        ),
    ]
