# Generated by Django 4.2.5 on 2023-09-30 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyecto_cupos_disponibles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='cupo_maximo',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='cupo_minimo',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='cupos_disponibles',
        ),
    ]
