# Generated by Django 4.2.5 on 2023-10-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_proyecto_cupos_disponibles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='cupos_disponibles',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='cupos_disponibles_proyecto',
            field=models.IntegerField(default=30),
        ),
    ]
