# Generated by Django 4.2.5 on 2023-10-01 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_inscripcion_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscripcion',
        ),
    ]
