# Generated by Django 4.2.5 on 2023-10-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_inscripcion_actividad_participantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='participantes',
        ),
    ]
