# Generated by Django 4.2.5 on 2023-10-02 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_remove_actividad_participantes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscripcion',
        ),
    ]
