# Generated by Django 4.2.5 on 2023-10-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='cupos_disponibles',
            field=models.IntegerField(default=20),
        ),
    ]
