# Generated by Django 4.2.6 on 2023-10-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_alter_actividad_cupos_disponibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='imagen_actividad',
            field=models.ImageField(blank=True, null=True, upload_to='actividades'),
        ),
    ]
