# Generated by Django 4.2.6 on 2023-10-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen_noticia',
            field=models.ImageField(blank=True, null=True, upload_to='noticias'),
        ),
    ]
